name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  pypi_release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish to pypi
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{"{{"}} secrets.pypi_api_token {{"}}"}}
          # https://pypi.org/help/#apitoken
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
        run: |
          poetry publish --build